### ISSUE TITLE
File "/data/data/com.termux/files/home/moonbix-bot/bot/core/tapper.py", line 800, in run     await self.play_game(session)   File "/data/data/com.termux/files/home/moonbix-bot/bot/core/tapper.py", line 678, in play_game     from bot.core.solver.captcha_solver import solve_captcha ModuleNotFoundError: No module named 'bot.core.solver.captcha_solver'

### ISSUE THREAD

**Issue by kagushin** [vanhbakaa/moonbix-bot#58]
File "/data/data/com.termux/files/home/moonbix-bot/bot/core/tapper.py", line 800, in run
    await self.play_game(session)
  File "/data/data/com.termux/files/home/moonbix-bot/bot/core/tapper.py", line 678, in play_game
    from bot.core.solver.captcha_solver import solve_captcha
ModuleNotFoundError: No module named 'bot.core.solver.captcha_solver'

plis fix

**Comment by vanhbakaa** [comment]
use correct python version in readme.md. read before you ask anything bro

**Comment by miliardov** [comment]
> File "/data/data/com.termux/files/home/moonbix-bot/bot/core/tapper.py", line 800, in run await self.play_game(session) File "/data/data/com.termux/files/home/moonbix-bot/bot/core/tapper.py", line 678, in play_game from bot.core.solver.captcha_solver import solve_captcha ModuleNotFoundError: No module named 'bot.core.solver.captcha_solver'
> 
> plis fix

Antivirus deleted some file that it detects as trojan-infected from the solver folder. I have the same thing. I'm afraid to return this file since it has a trojan in it.

**Comment by miliardov** [comment]
> use correct python version in readme.md. read before you ask anything bro

It's not the python version, it's the missing file with trojan.

Traceback (most recent call last):
  File "C:\Users\38099\Desktop\Скрипт\Готовые кода\vanhbakaa_moonbix\bot\core\tapper.py", line 800, in run
    await self.play_game(session)
  File "C:\Users\38099\Desktop\Скрипт\Готовые кода\vanhbakaa_moonbix\bot\core\tapper.py", line 678, in play_game
    from bot.core.solver.captcha_solver import solve_captcha
  File "captcha_solver.pyx", line 4, in init bot.core.solver.captcha_solver
ModuleNotFoundError: No module named 'bot.core.solver.captcha.payload'
2024-10-07 12:23:30 | ERROR    | 813 - 2my | Unknown error: No module named 'bot.core.solver.captcha.payload'
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x00000187A6123810>

ImportError: DLL load failed while importing payload: The operation was not completed successfully because the file contains a virus or potentially unwanted program.

Detected: Trojan:Win32/Wacatac.B!ml
Information: This dangerous program executes the attacker's commands.
file: C:\Users\38099\Desktop\Script\vanhbakaa_moonbix\bot\core\solver\captcha\payload.cp311-win_amd64.pyd

**Comment by vanhbakaa** [comment]
Antivirus software often uses heuristic techniques to detect potential threats by analyzing the behavior and structure of files rather than relying solely on known malware signatures. Since compiled .pyd files (which are similar to .dll files for Windows) are binary executables, the antivirus may flag them due to the way they interact with the system or because their internal structure resembles known malware patterns.You can use spy hunter 5 to scan this folder it's fine

**Comment by meliqa92** [comment]
how solve captcha problem have you any idea?
